let User,CustomErrorHandler;_fd8‍.x([["default",()=>_fd8‍.o]]);_fd8‍.w("../../models",[["User",["User"],function(v){User=v}]]);_fd8‍.w("../../services/CustomErrorHandler",[["default",["CustomErrorHandler"],function(v){CustomErrorHandler=v}]]);


const userController = {
  async me(req, res, next) {
    try {

      const user = await User.findOne({ _id: req.user._id });

      if (!user) {
        return next(CustomErrorHandler.notFound());
      }
      res.json(user);
    } catch (err) { return next(err)}
   
  },
};

_fd8‍.d(userController);
