let DEBUG_MODE,ValidationError,CutomErrorHandler;_da3‍.x([["default",()=>_da3‍.o]]);_da3‍.w("../config",[["DEBUG_MODE",["DEBUG_MODE"],function(v){DEBUG_MODE=v}]]);_da3‍.w("joi",[["ValidationError",["ValidationError"],function(v){ValidationError=v}]]);_da3‍.w("../services/CustomErrorHandler",[["default",["CutomErrorHandler"],function(v){CutomErrorHandler=v}]]);



const errorHandler = (err, req, res, next) => {
  let statusCode = 500;
  let data = {
    message: "Internal server error",
    ...(DEBUG_MODE === "true" && {
      originalError: err.message,
    }),
  };

  if (err instanceof ValidationError) {
    statusCode = 422;
    data = {
      message: err.message,
    };
  }

  if(err instanceof CutomErrorHandler)

  return res.status(statusCode).json(data);
};
_da3‍.d(errorHandler);
